### ISSUE TITLE
`Exception not caught: You need to upgrade fzf` when using latest version of skim

### ISSUE THREAD

**Issue by kageru** [lotabout/skim.vim#23] opened 2022-11-17 21:56 UTC
Trying to open the file list, I get this error:
```
Error detected while processing function fzf#vim#files[15]..<SNR>108_fzf[1]..<SNR>108_check_requirements[18]..function fzf#vim
#files[15]..<SNR>108_fzf[1]..<SNR>108_check_requirements:
line   18:
E605: Exception not caught: You need to upgrade fzf. Found:  (sk). Required: 0.9.3 or above.
```
I assume the problem is the [version check here](https://github.com/lotabout/skim.vim/blob/83faea7f2581005d4adc9256ec76e0fe3f8a15e6/autoload/fzf/vim.vim#L51) which checks for version 0.9, finds 0.10, and, if I understand the code correctly, fails because it compares each character individually and `1 < 9`.

**Comment by rkanati** [comment] 2022-11-20 21:02
actually this is related to lotabout/skim#490 - `sk --version` prints the wrong thing, now, which breaks the parsing.

**Comment by rkanati** [comment] 2022-11-20 21:10
note: https://github.com/wks/skim.vim appears to contain a fix

**Comment by LoricAndre** [comment] 2024-11-22 21:42
I can't reproduce this with the latest version of skim (0.11.11), I'm closing the issue. Please reopen if you are able to reproduce this after updating skim

**Closed as completed by LoricAndre** 2024-11-22 21:42 UTC
